export const CITY_KEYWORDS: string[] = [
  // Waste & sanitation
  "smeće",
  "smece",
  "smeća",
  "smeca",
  "otpad",
  "deponij",
  "kontejner",
  "kanalizacija",
  "kanalizacij",
  "fekalij",
  "septička",
  "septicka",
  "odvodnja",
  // Water
  "voda",
  "vodovod",
  "vodoopskrb",
  "vodoinstalacij",
  "hidrofor",
  "poplava",
  "poplavljen",
  "izljev",
  "curenje",
  "procurio",
  "procurila",
  "suša",
  "susa",
  "nestanak vode",
  // Electricity & gas
  "struja",
  "električna",
  "elektricna",
  "HEP",
  "rasvjeta",
  "osvjetljenje",
  "javna rasvjeta",
  "kvar struje",
  "nestanak struje",
  "plin",
  "plinara",
  "plinovod",
  "plinska",
  "plinski",
  // Roads & traffic
  "cesta",
  "asfalt",
  "kolnik",
  "nogostup",
  "pločnik",
  "plocnik",
  "oštećenje kolnika",
  "ostecenje",
  "semafori",
  "semafor",
  "prometni znak",
  "oznake",
  "zebra prijelaz",
  "zastoj",
  "gužva",
  "guzva",
  "prometna nesreća",
  "prometna nesreca",
  // Parking
  "parking",
  "parkiralište",
  "parkiraliste",
  "parkiranje",
  "parkiran",
  "zauzeto parkirno",
  "nepropisno parkiran",
  // Public transport
  "promet Split",
  "Promet d.o.o",
  "linija broj",
  "autobusni kolodvor",
  "red voznje",
  "tramvaj",
  // Green areas & environment
  "zelenilo",
  "park",
  "drveće",
  "drvece",
  "zelena površina",
  "travnjak",
  "košnja",
  "zagađenje",
  "zagadjenje",
  "onečišćenje",
  "oneciscenje",
  "emisije",
  "buka",
  "galama",
  "bušenje",
  "busenje",
  "gradilište",
  "gradiliste",
  // City administration & services
  "Split",
  "Grad Split",
  "gradonačelnik",
  "gradonacelnik",
  "gradska uprava",
  "komunalna",
  "komunalni",
  "inspekcija",
  "urbanizam",
  "lokacija",
  "ulica",
  "trg",
  "kvart",
  "infrastruktura",
  "javna površina",
  "javna povrsina",
  "renovacija",
  "rekonstrukcija",
  "sanacija",
  // Buildings & public spaces
  "fasada",
  "zgrade",
  "stanari",
  "zgrada",
  "lift",
  "dizalo",
  "bespravna gradnja",
  "bespravno",
  "rušenje",
  "rusenje",
  "odron",
  "klizište",
  "kliziste",
  // Sea & coastal
  "more",
  "onečišćenje mora",
];
